services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Digicademy\Academy\:
    resource: '../../academy/Classes/*'

#  GeorgRinger\News\Domain\Model\News: '@Digicademy\Academy\Domain\Model\News'
#  GeorgRinger\Eventnews\Domain\Model\News: '@Digicademy\Academy\Domain\Model\Events'
